<a href="https://colab.research.google.com/github/shiva90140/github-slideshow/blob/dependabot%2Fbundler%2Faddressable-2.8.1/M_SHIVAKUMAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[2,8,9],[10,2,4]]])
print(arr)
print("\nSorted array:\n")
print(np.sort(arr))
print("\nUsing where function:\n")
x=np.where(arr == 2)
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 2  8  9]
  [10  2  4]]]

Sorted array:

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 2  8  9]
  [ 2  4 10]]]

Using where function:

(array([0, 1, 1]), array([0, 0, 1]), array([1, 0, 1]))


In [12]:
print("Done")

Done
